apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  ports:
  - port: 9696
    protocol: TCP
    targetPort: 9696
    name: webui
  selector:
    run: prowlarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prowlarr
  template:
    metadata:
      labels:
        run: prowlarr
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Denver
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: linuxserver/prowlarr
        name: prowlarr
        ports:
        - containerPort: 9696
          name: webui
          #        livenessProbe:
          #          exec:
          #            command:
          #            - /bin/sh
          #            - -c
          #            - curl "http://localhost:7878/radarr/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          #          initialDelaySeconds: 30
          #          periodSeconds: 10
          #        readinessProbe:
          #          exec:
          #            command:
          #            - /bin/sh
          #            - -c
          #            - curl "http://localhost:7878/radarr/api/system/status?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          #          initialDelaySeconds: 30
          #          periodSeconds: 10
        volumeMounts: 
        - mountPath: /config 
          name: htpc-home
          subPath: prowlarr

